### ISSUE TITLE
Adding expectations for slack channels

### ISSUE THREAD

**Issue by spflanagan** [flanagan-lab/flanagan-lab.github.io#2]
We have several channels on Slack that have some expectation that they'll be used, including #lone-worker, #working-from-home, and #goals. Should we include expectations for the use of these channels in the lab manual? If so, what should those expectations be?

**Comment by ERBeasley** [comment]
Add in expectations around using profile status updates, especially sick, vacation, or remote work (but can also include custom stuff)

**Comment by spflanagan** [comment]
Accomplished in [this pull request](https://github.com/flanagan-lab/flanagan-lab.github.io/pull/5)
