### ISSUE TITLE
Are the timelines for deadlines appropriate?

### ISSUE THREAD

**Issue by spflanagan** [flanagan-lab/flanagan-lab.github.io#3]
I specify some timelines in the lab manual for how long it will take me to look at the items, and there is a request for deadlines to be added to the calendar (which I never really implemented for you!). Are these timelines appropriate? What is the best way to manage shared deadlines? 

Should we specify a preferred approach for managing shared documents in the lab manual? If so, what is that preferred approach?

**Comment by ERBeasley** [comment]
This is something we would like to discuss as a group in the next lab meeting

**Comment by ERBeasley** [comment]
- your responsibility to ensure Sarah knows what she needs to do and when. 
- your emergency is not my emergency

also: add summary of meetings to agenda

**Comment by spflanagan** [comment]
Resolved in pull request https://github.com/flanagan-lab/flanagan-lab.github.io/pull/6
